<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MobilSeeder extends Seeder
{
    public function run()
    {
        DB::table('mobil')->insert([
            [
                'gambar' => 'gambar/agya.jpg',
                'nama_mobil' => 'All New Agya',
                'tipe_mobil' => '1.2 G',
                'merk_mobil' => 'Toyota',
                'warna' => 'putih',
                'transmisi' => 'manual',
                'stok' => '10',
                'harga' => 194200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/agya_gr.jpg',
                'nama_mobil' => 'All New Agya',
                'tipe_mobil' => '1.2 GR Sport',
                'merk_mobil' => 'Toyota',
                'warna' => 'merah',
                'transmisi' => 'matic',
                'stok' => '7',
                'harga' => 255000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/calya_std.jpg',
                'nama_mobil' => 'New Calya',
                'tipe_mobil' => '1.2 E STD',
                'merk_mobil' => 'Toyota',
                'warna' => 'hitam',
                'transmisi' => 'manual',
                'stok' => '15',
                'harga' => 190400000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/calya_g.jpg',
                'nama_mobil' => 'New Calya',
                'tipe_mobil' => '1.2 G',
                'merk_mobil' => 'Toyota',
                'warna' => 'putih',
                'transmisi' => 'matic',
                'stok' => '8',
                'harga' => 212700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/yaris_cross.jpg',
                'nama_mobil' => 'All New Yaris Cross',
                'tipe_mobil' => '1.5 G MT',
                'merk_mobil' => 'Toyota',
                'warna' => 'merah',
                'transmisi' => 'manual',
                'stok' => '6',
                'harga' => 360800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/yaris_cross_tss.jpg',
                'nama_mobil' => 'All New Yaris Cross',
                'tipe_mobil' => '1.5 HV TSS GR Package',
                'merk_mobil' => 'Toyota',
                'warna' => 'putih',
                'transmisi' => 'matic',
                'stok' => '5',
                'harga' => 459000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/veloz.jpg',
                'nama_mobil' => 'Veloz',
                'tipe_mobil' => '1.5',
                'merk_mobil' => 'Toyota',
                'warna' => 'hitam',
                'transmisi' => 'manual',
                'stok' => '7',
                'harga' => 310500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/veloz_premium.jpg',
                'nama_mobil' => 'Veloz',
                'tipe_mobil' => '1.5 Q Premium Lux',
                'merk_mobil' => 'Toyota',
                'warna' => 'merah',
                'transmisi' => 'matic',
                'stok' => '5',
                'harga' => 352750000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/cross.jpg',
                'nama_mobil' => 'Cross 1.8',
                'tipe_mobil' => 'HYB PC',
                'merk_mobil' => 'Toyota',
                'warna' => 'putih',
                'transmisi' => 'manual',
                'stok' => '6',
                'harga' => 573700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/innova_reborn.jpg',
                'nama_mobil' => 'Innova Reborn',
                'tipe_mobil' => '2.0 G',
                'merk_mobil' => 'Toyota',
                'warna' => 'hitam',
                'transmisi' => 'manual',
                'stok' => '5',
                'harga' => 386450000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/fortuner.jpg',
                'nama_mobil' => 'Fortuner',
                'tipe_mobil' => '2.7 SRZ 4x2',
                'merk_mobil' => 'Toyota',
                'warna' => 'merah',
                'transmisi' => 'matic',
                'stok' => '3',
                'harga' => 624200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/camry.jpg',
                'nama_mobil' => 'Camry',
                'tipe_mobil' => '2.5 V',
                'merk_mobil' => 'Toyota',
                'warna' => 'putih',
                'transmisi' => 'matic',
                'stok' => '4',
                'harga' => 682900000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/hilux.jpg',
                'nama_mobil' => 'New Hilux',
                'tipe_mobil' => '2.4 E 4x4',
                'merk_mobil' => 'Toyota',
                'warna' => 'hitam',
                'transmisi' => 'manual',
                'stok' => '8',
                'harga' => 450700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/avanza.jpg',
                'nama_mobil' => 'Avanza',
                'tipe_mobil' => '1.5 G',
                'merk_mobil' => 'Toyota',
                'warna' => 'putih',
                'transmisi' => 'matic',
                'stok' => '10',
                'harga' => 294600000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/alphard.jpg',
                'nama_mobil' => 'New Alphard',
                'tipe_mobil' => '2.5 X Hybrid',
                'merk_mobil' => 'Toyota',
                'warna' => 'merah',
                'transmisi' => 'matic',
                'stok' => '2',
                'harga' => 1685700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/zenix.jpg',
                'nama_mobil' => 'Innova Zenix',
                'tipe_mobil' => '2.0 V',
                'merk_mobil' => 'Toyota',
                'warna' => 'putih',
                'transmisi' => 'manual',
                'stok' => '6',
                'harga' => 478700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/fortuner_gr.jpg',
                'nama_mobil' => 'Fortuner',
                'tipe_mobil' => 'GR Sport',
                'merk_mobil' => 'Toyota',
                'warna' => 'hitam',
                'transmisi' => 'matic',
                'stok' => '5',
                'harga' => 749200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/agya_lux.jpg',
                'nama_mobil' => 'All New Agya',
                'tipe_mobil' => '1.2 G Lux',
                'merk_mobil' => 'Toyota',
                'warna' => 'merah',
                'transmisi' => 'matic',
                'stok' => '7',
                'harga' => 217700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/avanza_15g.jpg',
                'nama_mobil' => 'Avanza',
                'tipe_mobil' => '1.5 G',
                'merk_mobil' => 'Toyota',
                'warna' => 'hitam',
                'transmisi' => 'manual',
                'stok' => '9',
                'harga' => 292800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'gambar/rush.jpg',
                'nama_mobil' => 'New Rush',
                'tipe_mobil' => '1.5 GR Sport',
                'merk_mobil' => 'Toyota',
                'warna' => 'putih',
                'transmisi' => 'matic',
                'stok' => '8',
                'harga' => 322300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
